language: go

go:
  - 1.6

env:
  - GO15VENDOREXPERIMENT=1

install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/Masterminds/glide
  - glide install
  - go install .

  # For coveralls support.
  - go get github.com/mattn/goveralls

script:
  - golint -min_confidence 0.0 $PROJECT_GOPATH
  - go vet .
  - go test -v -cover $(go list ./... | grep -v '/vendor/') # Raw test command.
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN -v
